#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KibaApp.Resource", IsApplication=true)]

namespace KibaApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::KibaApp.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::KibaApp.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::KibaApp.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ic_launcher_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int area_above_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int area_above_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int area_below_left = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int area_below_right = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int rootblock_default_bg = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rootblock_icon_add = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int rootblock_icon_add_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rootblock_icon_add_selected = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rootblock_icon_clear = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rootblock_icon_clear_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int rootblock_icon_clear_selected = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int rootblock_icon_download = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int rootblock_icon_download_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rootblock_icon_download_selected = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rootblock_icon_set = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rootblock_icon_set_bg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int rootblock_icon_set_selected = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int scan_light = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int btnCancelScan = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int btnList = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int btnScan = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int contentFrame = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int download_btn = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int fragment_menu = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int ivScanning = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int rlscan = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int MainActivity = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MenuFragment = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ZxingOverlay = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int zxingscanneractivitylayout = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int zxingscannerfragmentlayout = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_launcher_foreground = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_launcher_round = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
